### ISSUE TITLE
Traceur compile has changed

### ISSUE THREAD

**Issue by seangenabe** [UltCombo/traceuroso#2]
It seems that `require('traceur').compile` now just returns a string instead of an object.

Using traceur@0.0.74.

**Comment by UltCombo** [comment]
fixed by aee0f389465e2c1e25a164991efd6e4d27a890f0, released in traceuroso v0.0.5.
Also, traceuroso is now deprecated in favor of [slush-es20xx](https://github.com/es6rocks/slush-es20xx).
